---
- name: Validate HTTPD installation on all hosts
  hosts: all
  gather_facts: no
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: "/home/mdc/.ssh/id_rsa"
  tasks:

    - name: Ensure the system is reachable
      ping:

    - name: Check if httpd is installed
      command: rpm -q httpd
      register: httpd_check
      ignore_errors: yes

    - name: Report the status of httpd
      debug:
        msg: >
          HTTPD is {{ 'installed' if httpd_check.rc == 0 else 'not installed' }}

