- name: Configure web server
  hosts: all
  become: yes
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: /home/mdc/.ssh/id_rsa
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Upload redhat.png
      copy:
        src: redhat.png
        dest: /var/www/html/redhat.png
        mode: '0644'

    - name: Set custom index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>RHUG Demo</title>
          </head>
          <body>
              <img src="redhat.png" alt="Red Hat Logo" style="width:200px;height:auto;">
              <h1>Birmingham, AL - RHUG is awesome</h1>
              <p>{{ inventory_hostname }}</p>
          </body>
          </html>

